name: Acquire activation file

on:
  workflow_dispatch: {}

jobs:
  activation-android:
    name: Request manual activation file for android
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.11f1-android-0.15.0
    env:
      DOTNET_ROOT: "/opt/unity/Editor/Data/NetCore/Sdk-2.2.107"
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: android-license.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}

  activation-webgl:
    name: Request manual activation file for webgl
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-2020.3.11f1-webgl-0.15.0
    env:
      DOTNET_ROOT: "/opt/unity/Editor/Data/NetCore/Sdk-2.2.107"
    steps:
      # Request manual activation file
      - name: Request manual activation file
        id: getManualLicenseFile
        uses: game-ci/unity-request-activation-file@v2
      # Upload artifact (Unity_v20XX.X.XXXX.alf)
      - name: Expose as artifact
        uses: actions/upload-artifact@v2
        with:
          name: webgl-license.alf
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
